//app.js
App({
  onLaunch(){
    console.log('app--onLaunch')
  },
  onShow(){
    console.log('app--onShow')
  },
  onHide(){
    console.log('app--onHide')
  },
  onError(){
    console.log('app--onError')
  },
  onPageNotFound(){
    console.log('app--onPageNotFound')
  }
})